apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spi-vault

resources:
  - https://github.com/redhat-appstudio/service-provider-integration-operator/config/vault/openshift?ref=45fa68db56318d2e729010f561680008fe2f64b9
